python xitex.py 0 &
python xitex.py 1 &
python xitex.py 2 &
python xitex.py 3 &
python xitex.py 4 &
python xitex.py 5 &
python xitex.py 6 &
python xitex.py 7 &
python xitex.py 8 &
python xitex.py 9 &
python xitex.py 10 &
python xitex.py 11 &
python xitex.py 12 &
python xitex.py 13 &
python xitex.py 14 &
python xitex.py 15 &
python xitex.py 16 &
python xitex.py 17 &
python xitex.py 18 &