nohup python xitex.py 0 &
nohup python xitex.py 1 &
nohup python xitex.py 2 &
nohup python xitex.py 3 &
nohup python xitex.py 4 &
nohup python xitex.py 5 &
nohup python xitex.py 6 &
nohup python xitex.py 7 &
nohup python xitex.py 8 &
nohup python xitex.py 9 &
nohup python xitex.py 10 &
nohup python xitex.py 11 &
nohup python xitex.py 12 &
nohup python xitex.py 13 &
nohup python xitex.py 14 &
nohup python xitex.py 15 &
nohup python xitex.py 16 &
nohup python xitex.py 17 &
nohup python xitex.py 18 &